create table items (
	id INT,
	i_name VARCHAR(50),
	price VARCHAR(50)
);
insert into items (id, i_name, price) values (1, 'Lid - 10,12,16 Oz', '$158.28');
insert into items (id, i_name, price) values (2, 'Bread - Roll, Whole Wheat', '$872.93');
insert into items (id, i_name, price) values (3, 'Tuna - Fresh', '$931.49');
insert into items (id, i_name, price) values (4, 'Parsley - Dried', '$393.03');
insert into items (id, i_name, price) values (5, 'Plastic Arrow Stir Stick', '$825.38');
insert into items (id, i_name, price) values (6, 'Jam - Strawberry, 20 Ml Jar', '$992.36');
insert into items (id, i_name, price) values (7, 'Pasta - Penne, Rigate, Dry', '$523.09');
insert into items (id, i_name, price) values (8, 'Pop - Club Soda Can', '$160.21');
insert into items (id, i_name, price) values (9, 'Tuna - Bluefin', '$635.03');
insert into items (id, i_name, price) values (10, 'Pastry - Choclate Baked', '$184.44');
insert into items (id, i_name, price) values (11, 'Wine - White, Ej', '$644.96');
insert into items (id, i_name, price) values (12, 'Crab Meat Claw Pasteurise', '$171.00');
insert into items (id, i_name, price) values (13, 'Milk - Chocolate 500ml', '$798.39');
insert into items (id, i_name, price) values (14, 'Tuna - Sushi Grade', '$373.90');
insert into items (id, i_name, price) values (15, 'Tendrils - Baby Pea, Organic', '$389.27');
insert into items (id, i_name, price) values (16, 'Vanilla Beans', '$681.69');
insert into items (id, i_name, price) values (17, 'Beef - Kobe Striploin', '$613.70');
insert into items (id, i_name, price) values (18, 'Soup - Campbells, Lentil', '$895.83');
insert into items (id, i_name, price) values (19, 'Shrimp - 31/40', '$595.18');
insert into items (id, i_name, price) values (20, 'Rye Special Old', '$630.56');
insert into items (id, i_name, price) values (21, 'Mushroom - Crimini', '$780.26');
insert into items (id, i_name, price) values (22, 'Pernod', '$600.27');
insert into items (id, i_name, price) values (23, 'Pasta - Lasagna Noodle, Frozen', '$732.00');
insert into items (id, i_name, price) values (24, 'Beef - Tenderloin Tails', '$640.17');
insert into items (id, i_name, price) values (25, 'Salt - Sea', '$336.03');
insert into items (id, i_name, price) values (26, 'Dc - Frozen Momji', '$335.44');
insert into items (id, i_name, price) values (27, 'Chocolate - Dark', '$956.51');
insert into items (id, i_name, price) values (28, 'Skirt - 29 Foot', '$789.03');
insert into items (id, i_name, price) values (29, 'Wine - Prosecco Valdobienne', '$219.00');
insert into items (id, i_name, price) values (30, 'Chicken - Whole Fryers', '$359.56');
insert into items (id, i_name, price) values (31, 'Soup - Verve - Chipotle Chicken', '$357.41');
insert into items (id, i_name, price) values (32, 'Sauce Bbq Smokey', '$485.88');
insert into items (id, i_name, price) values (33, 'Gingerale - Schweppes, 355 Ml', '$136.53');
insert into items (id, i_name, price) values (34, 'Five Alive Citrus', '$281.53');
insert into items (id, i_name, price) values (35, 'Sambuca - Opal Nera', '$531.92');
insert into items (id, i_name, price) values (36, 'Squid - Tubes / Tenticles 10/20', '$143.51');
insert into items (id, i_name, price) values (37, 'Wine - Black Tower Qr', '$309.53');
insert into items (id, i_name, price) values (38, 'Tequila Rose Cream Liquor', '$357.57');
insert into items (id, i_name, price) values (39, 'Artichoke - Bottom, Canned', '$360.53');
insert into items (id, i_name, price) values (40, 'Soup - Campbells Bean Medley', '$940.71');
insert into items (id, i_name, price) values (41, 'Buffalo - Short Rib Fresh', '$315.57');
insert into items (id, i_name, price) values (42, 'Muffin Carrot - Individual', '$708.72');
insert into items (id, i_name, price) values (43, 'Coffee Beans - Chocolate', '$976.78');
insert into items (id, i_name, price) values (44, 'Chicken Breast Wing On', '$458.20');
insert into items (id, i_name, price) values (45, 'Chef Hat 25cm', '$819.26');
insert into items (id, i_name, price) values (46, 'Cake Sheet Combo Party Pack', '$108.11');
insert into items (id, i_name, price) values (47, 'Energy Drink Red Bull', '$350.66');
insert into items (id, i_name, price) values (48, 'Soup - Campbells, Butternut', '$924.98');
insert into items (id, i_name, price) values (49, 'Anchovy Fillets', '$415.96');
insert into items (id, i_name, price) values (50, 'Wine - Blue Nun Qualitatswein', '$764.34');
insert into items (id, i_name, price) values (51, 'Vaccum Bag 10x13', '$311.30');
insert into items (id, i_name, price) values (52, 'Cookie - Oatmeal', '$304.57');
insert into items (id, i_name, price) values (53, 'Chevere Logs', '$772.78');
insert into items (id, i_name, price) values (54, 'Scampi Tail', '$917.40');
insert into items (id, i_name, price) values (55, 'Sauerkraut', '$506.21');
insert into items (id, i_name, price) values (56, 'Dried Cranberries', '$899.98');
insert into items (id, i_name, price) values (57, 'Cake - Night And Day Choclate', '$828.43');
insert into items (id, i_name, price) values (58, 'Nantucket - 518ml', '$202.08');
insert into items (id, i_name, price) values (59, 'Pastry - French Mini Assorted', '$143.59');
insert into items (id, i_name, price) values (60, 'Steel Wool S.o.s', '$869.64');
insert into items (id, i_name, price) values (61, 'Truffle - Peelings', '$897.77');
insert into items (id, i_name, price) values (62, 'Wine - Magnotta - Red, Baco', '$786.70');
insert into items (id, i_name, price) values (63, 'Iced Tea - Lemon, 460 Ml', '$988.50');
insert into items (id, i_name, price) values (64, 'Wine La Vielle Ferme Cote Du', '$533.98');
insert into items (id, i_name, price) values (65, 'Wine - Mas Chicet Rose, Vintage', '$420.85');
insert into items (id, i_name, price) values (66, 'Chocolate - Semi Sweet', '$355.11');
insert into items (id, i_name, price) values (67, 'Cheese - Mozzarella, Shredded', '$594.21');
insert into items (id, i_name, price) values (68, 'Cookies Cereal Nut', '$464.68');
insert into items (id, i_name, price) values (69, 'Sugar - Invert', '$355.95');
insert into items (id, i_name, price) values (70, 'Lid Coffee Cup 8oz Blk', '$267.54');
insert into items (id, i_name, price) values (71, 'Oil - Coconut', '$647.77');
insert into items (id, i_name, price) values (72, 'Sobe - Tropical Energy', '$542.12');
insert into items (id, i_name, price) values (73, 'Fish - Bones', '$517.86');
insert into items (id, i_name, price) values (74, 'Campari', '$515.18');
insert into items (id, i_name, price) values (75, 'Cranberry Foccacia', '$958.14');
insert into items (id, i_name, price) values (76, 'Wine - Delicato Merlot', '$963.62');
insert into items (id, i_name, price) values (77, 'Tarragon - Fresh', '$607.44');
insert into items (id, i_name, price) values (78, 'Cod - Black Whole Fillet', '$655.68');
insert into items (id, i_name, price) values (79, 'Pickerel - Fillets', '$229.70');
insert into items (id, i_name, price) values (80, 'French Kiss Vanilla', '$495.50');
insert into items (id, i_name, price) values (81, 'Appetizer - Shrimp Puff', '$177.10');
insert into items (id, i_name, price) values (82, 'Cornish Hen', '$226.66');
insert into items (id, i_name, price) values (83, 'Tomato - Tricolor Cherry', '$562.85');
insert into items (id, i_name, price) values (84, 'Guinea Fowl', '$658.99');
insert into items (id, i_name, price) values (85, 'Beer - Rickards Red', '$368.56');
insert into items (id, i_name, price) values (86, 'Shiratamako - Rice Flour', '$921.43');
insert into items (id, i_name, price) values (87, 'Corn - Mini', '$315.27');
insert into items (id, i_name, price) values (88, 'Nut - Walnut, Pieces', '$409.52');
insert into items (id, i_name, price) values (89, 'Beans - Fava, Canned', '$628.97');
insert into items (id, i_name, price) values (90, 'Longos - Greek Salad', '$379.83');
insert into items (id, i_name, price) values (91, 'Apple - Royal Gala', '$325.08');
insert into items (id, i_name, price) values (92, 'Ginger - Fresh', '$460.05');
insert into items (id, i_name, price) values (93, 'Corn - Mini', '$875.81');
insert into items (id, i_name, price) values (94, 'Calypso - Pineapple Passion', '$114.40');
insert into items (id, i_name, price) values (95, 'Chicken - Ground', '$703.37');
insert into items (id, i_name, price) values (96, 'Lamb - Shoulder, Boneless', '$181.77');
insert into items (id, i_name, price) values (97, 'Energy - Boo - Koo', '$285.02');
insert into items (id, i_name, price) values (98, 'Southern Comfort', '$529.28');
insert into items (id, i_name, price) values (99, 'Wine - Pinot Noir Stoneleigh', '$566.98');
insert into items (id, i_name, price) values (100, 'Appetizer - Veg Assortment', '$749.78');
