drop table if exists payments;
create table if not exists payments(
id serial primary key,
customer_id i);
drop table if exists employee;

create table if not exists employee(
id serial  primary key,
username varchar(50) NOT NULL UNIQUE,
password varchar(30) not null,
first_name varchar(100),
last_name varchar(100),
email varchar(150),
e_role integer
);
drop table if exists customer;
create table if not exists customer(
id serial primary key,
username varchar(50) NOT NULL UNIQUE,
password varchar(30) not null,
balance integer
);
select * from items ;
delete from items where i_name = 'pen';
drop table if exists items;
delete from items where i_name='Bread - Roll, Whole Wheat';

create table if not exists items(
id serial primary key,
i_name varchar(50),
price integer,
owned_state boolean,
customer_id integer references customer(id)
);
drop table if exists offer;
create table if not exists offer(
id serial primary key,
c_id integer references customer(id),
i_id integer references items(id),
amount integer,
accepted boolean default null,
offer_date date
);
select i.i_name  from items i join offer o on i.customer_id = o.c_id ;
select * from items where customer_id= 1;
select c.id, c.i_name, c.owned_state from offer t join items c on t.c_id = c.customer_id where c.customer_id = 1;
select t.id, t.i_id,  t.c_id  from offer t join items c on t.c_id = c.id where c.id = 1;
update offer set offer_date = '2022-06-10' where accepted=true;
insert into offer (c_id, i_id,amount) values (1, 2, 158.28);
insert into offer (c_id, i_id,amount) values (1, 1, 158.28);
insert into offer (c_id, i_id,amount) values (2, 2, 158.28);
insert into offer (c_id, i_id,amount) values (3, 2, 158.28);
insert into offer (c_id, i_id,amount) values (4, 1, 158.28);
insert into offer (c_id, i_id,amount) values (2, 7, 158.28);

insert into items ( i_name, price) values ('flask', 200);
insert into items ( i_name, price) values ('cup', 100);
insert into items ( i_name, price) values ('table', 600);
insert into items ( i_name, price) values ('tv', 400);
insert into items ( i_name, price) values ('car', 2000);
insert into items ( i_name, price) values ('mobile', 1000);
insert into items ( i_name, price) values ('carpet', 200);
insert into items ( i_name, price) values ( 'Bread - Roll, Whole Wheat', 872.93);
insert into items ( i_name, price) values ('Tuna - Fresh', 931.49);
insert into items ( i_name, price) values ( 'Parsley - Dried', 393.03);
insert into items ( i_name, price) values ( 'Plastic Arrow Stir Stick', 825.38);
insert into items ( i_name, price) values ( 'Jam - Strawberry, 20 Ml Jar', 992.36);
insert into items ( i_name, price) values ( 'Pasta - Penne, Rigate, Dry', 523.09);
insert into items ( i_name, price) values ( 'Pop - Club Soda Can', 160.21);
insert into items ( i_name, price) values ( 'Tuna - Bluefin', 635.03);
insert into items ( i_name, price) values ( 'Pastry - Choclate Baked', 184.44);
insert into items ( i_name, price) values ( 'Wine - White, Ej', 644.96);
insert into items (id, i_name, price) values (12, 'Crab Meat Claw Pasteurise', 171.00);
insert into items (id, i_name, price) values (13, 'Milk - Chocolate 500ml', 798.39);
insert into items (id, i_name, price) values (14, 'Tuna - Sushi Grade', 373.90);
insert into items (id, i_name, price) values (15, 'Tendrils - Baby Pea, Organic', 389.27);
insert into items (id, i_name, price) values (16, 'Vanilla Beans', 681.69);
insert into items (id, i_name, price) values (17, 'Beef - Kobe Striploin', 613.70);
insert into items (id, i_name, price) values (18, 'Soup - Campbells, Lentil', 895.83);
insert into items (id, i_name, price) values (19, 'Shrimp - 31/40', 595.18);
insert into items (id, i_name, price) values (20, 'Rye Special Old', 630.56);
insert into items (id, i_name, price) values (21, 'Mushroom - Crimini', 780.26);
insert into items (id, i_name, price) values (22, 'Pernod', 600.27);
insert into items (id, i_name, price) values (23, 'Pasta - Lasagna Noodle, Frozen', 732.00);
insert into items (id, i_name, price) values (24, 'Beef - Tenderloin Tails', 640.17);
insert into items (id, i_name, price) values (25, 'Salt - Sea', 336.03);
insert into items (id, i_name, price) values (26, 'Dc - Frozen Momji', 335.44);
insert into items (id, i_name, price) values (27, 'Chocolate - Dark', '$956.51');
insert into items (id, i_name, price) values (28, 'Skirt - 29 Foot', '$789.03');
insert into items (id, i_name, price) values (29, 'Wine - Prosecco Valdobienne', '$219.00');
insert into items (id, i_name, price) values (30, 'Chicken - Whole Fryers', '$359.56');
insert into items (id, i_name, price) values (31, 'Soup - Verve - Chipotle Chicken', '$357.41');
insert into items (id, i_name, price) values (32, 'Sauce Bbq Smokey', '$485.88');
insert into items (id, i_name, price) values (33, 'Gingerale - Schweppes, 355 Ml', '$136.53');
insert into items (id, i_name, price) values (34, 'Five Alive Citrus', '$281.53');
insert into items (id, i_name, price) values (35, 'Sambuca - Opal Nera', '$531.92');
insert into items (id, i_name, price) values (36, 'Squid - Tubes / Tenticles 10/20', '$143.51');
insert into items (id, i_name, price) values (37, 'Wine - Black Tower Qr', '$309.53');
insert into items (id, i_name, price) values (38, 'Tequila Rose Cream Liquor', '$357.57');
insert into items (id, i_name, price) values (39, 'Artichoke - Bottom, Canned', '$360.53');
insert into items (id, i_name, price) values (40, 'Soup - Campbells Bean Medley', '$940.71');
insert into items (id, i_name, price) values (41, 'Buffalo - Short Rib Fresh', '$315.57');
insert into items (id, i_name, price) values (42, 'Muffin Carrot - Individual', '$708.72');
insert into items (id, i_name, price) values (43, 'Coffee Beans - Chocolate', '$976.78');
insert into items (id, i_name, price) values (44, 'Chicken Breast Wing On', '$458.20');
insert into items (id, i_name, price) values (45, 'Chef Hat 25cm', '$819.26');
insert into items (id, i_name, price) values (46, 'Cake Sheet Combo Party Pack', '$108.11');
insert into items (id, i_name, price) values (47, 'Energy Drink Red Bull', '$350.66');
insert into items (id, i_name, price) values (48, 'Soup - Campbells, Butternut', '$924.98');
insert into items (id, i_name, price) values (49, 'Anchovy Fillets', '$415.96');
insert into items (id, i_name, price) values (50, 'Wine - Blue Nun Qualitatswein', '$764.34');
insert into items (id, i_name, price) values (51, 'Vaccum Bag 10x13', '$311.30');
insert into items (id, i_name, price) values (52, 'Cookie - Oatmeal', '$304.57');
insert into items (id, i_name, price) values (53, 'Chevere Logs', '$772.78');
insert into items (id, i_name, price) values (54, 'Scampi Tail', '$917.40');
insert into items (id, i_name, price) values (55, 'Sauerkraut', '$506.21');
insert into items (id, i_name, price) values (56, 'Dried Cranberries', '$899.98');
insert into items (id, i_name, price) values (57, 'Cake - Night And Day Choclate', '$828.43');
insert into items (id, i_name, price) values (58, 'Nantucket - 518ml', '$202.08');
insert into items (id, i_name, price) values (59, 'Pastry - French Mini Assorted', '$143.59');
insert into items (id, i_name, price) values (60, 'Steel Wool S.o.s', '$869.64');
insert into items (id, i_name, price) values (61, 'Truffle - Peelings', '$897.77');
insert into items (id, i_name, price) values (62, 'Wine - Magnotta - Red, Baco', '$786.70');
insert into items (id, i_name, price) values (63, 'Iced Tea - Lemon, 460 Ml', '$988.50');
insert into items (id, i_name, price) values (64, 'Wine La Vielle Ferme Cote Du', '$533.98');
insert into items (id, i_name, price) values (65, 'Wine - Mas Chicet Rose, Vintage', '$420.85');
insert into items (id, i_name, price) values (66, 'Chocolate - Semi Sweet', '$355.11');
insert into items (id, i_name, price) values (67, 'Cheese - Mozzarella, Shredded', '$594.21');
insert into items (id, i_name, price) values (68, 'Cookies Cereal Nut', '$464.68');
insert into items (id, i_name, price) values (69, 'Sugar - Invert', '$355.95');
insert into items (id, i_name, price) values (70, 'Lid Coffee Cup 8oz Blk', '$267.54');
insert into items (id, i_name, price) values (71, 'Oil - Coconut', '$647.77');
insert into items (id, i_name, price) values (72, 'Sobe - Tropical Energy', '$542.12');
insert into items (id, i_name, price) values (73, 'Fish - Bones', '$517.86');
insert into items (id, i_name, price) values (74, 'Campari', '$515.18');
insert into items (id, i_name, price) values (75, 'Cranberry Foccacia', '$958.14');
insert into items (id, i_name, price) values (76, 'Wine - Delicato Merlot', '$963.62');
insert into items (id, i_name, price) values (77, 'Tarragon - Fresh', '$607.44');
insert into items (id, i_name, price) values (78, 'Cod - Black Whole Fillet', '$655.68');
insert into items (id, i_name, price) values (79, 'Pickerel - Fillets', '$229.70');
insert into items (id, i_name, price) values (80, 'French Kiss Vanilla', '$495.50');
insert into items (id, i_name, price) values (81, 'Appetizer - Shrimp Puff', '$177.10');
insert into items (id, i_name, price) values (82, 'Cornish Hen', '$226.66');
insert into items (id, i_name, price) values (83, 'Tomato - Tricolor Cherry', '$562.85');
insert into items (id, i_name, price) values (84, 'Guinea Fowl', '$658.99');
insert into items (id, i_name, price) values (85, 'Beer - Rickards Red', '$368.56');
insert into items (id, i_name, price) values (86, 'Shiratamako - Rice Flour', '$921.43');
insert into items (id, i_name, price) values (87, 'Corn - Mini', '$315.27');
insert into items (id, i_name, price) values (88, 'Nut - Walnut, Pieces', '$409.52');
insert into items (id, i_name, price) values (89, 'Beans - Fava, Canned', '$628.97');
insert into items (id, i_name, price) values (90, 'Longos - Greek Salad', '$379.83');
insert into items (id, i_name, price) values (91, 'Apple - Royal Gala', '$325.08');
insert into items (id, i_name, price) values (92, 'Ginger - Fresh', '$460.05');
insert into items (id, i_name, price) values (93, 'Corn - Mini', '$875.81');
insert into items (id, i_name, price) values (94, 'Calypso - Pineapple Passion', '$114.40');
insert into items (id, i_name, price) values (95, 'Chicken - Ground', '$703.37');
insert into items (id, i_name, price) values (96, 'Lamb - Shoulder, Boneless', '$181.77');
insert into items (id, i_name, price) values (97, 'Energy - Boo - Koo', '$285.02');
insert into items (id, i_name, price) values (98, 'Southern Comfort', '$529.28');
insert into items (id, i_name, price) values (99, 'Wine - Pinot Noir Stoneleigh', '$566.98');
insert into items (id, i_name, price) values (100, 'Appetizer - Veg Assortment', '$749.78');
select * from employee;
select t.id, t.i_name, t.owned_state, t.customer_id , c.username from items t join customer c on t.customer_id = c.id where c.id = 2;
insert into items (i_name, price) values ('hcocking0', '9876');
insert into items (i_name, price) values ('dvalenta1', '45678');
select * from customer;
insert into employee (username, password) values ('aliaa', '12345');
select * from offer;
select amount from offer where offer_date >'2022-06-22' and offer_date <= DATEADD(now()  , -7,'2022-06-22' );
select sum(amount) as total from offer where accepted = true;

select * from customer where id = 1;
update offer set accepted = 'false' ;
delete from offer where i_id=2 and accepted !='false';
delete from offer where i_id=2 and (accepted = false or accepted is null) ;
insert into employee (username, password) values ('asmaa', '12345');
insert into employee (id, username, password) values (1, 'twanne0', '1IUXiY0');
insert into employee (id, username, password) values (2, 'fjerche1', 'A9ppQdspk3e');
insert into employee (id, username, password) values (3, 'pgrimsditch2', 'epv5gfUgd5');
insert into employee (id, username, password) values (4, 'bbaudrey3', 'qOKyzM2Pd');
insert into employee (id, username, password) values (5, 'bboanas4', 'X0FPntEN');
insert into employee (id, username, password) values (6, 'mdubble5', 'X1J3GRpuTqo');
insert into employee (id, username, password) values (7, 'ogian6', 'KDtCEkICMh');
insert into employee (id, username, password) values (8, 'jtoop7', 'QIpTcG');
insert into employee (id, username, password) values (9, 'mlipyeat8', 'WwHwdBL');
insert into employee (id, username, password) values (10, 'lfarrar9', 'DY3mFX5Rn');
insert into employee (id, username, password) values (11, 'mlanda', 'AdhenWQ');
insert into employee (id, username, password) values (12, 'nimlawb', '0p4KE4qkJGk');
insert into employee (id, username, password) values (13, 'wbolinc', 'a6FXXJWM5O');
insert into employee (id, username, password) values (14, 'jmatejicd', '36S8mz1I9RYz');
insert into employee (id, username, password) values (15, 'tdinnise', 'UwGRmExUHdZ');
insert into employee (id, username, password) values (16, 'dpagelf', 'P00FbVZ');
insert into employee (id, username, password) values (17, 'kkobusg', 'EeMKJZd7nEz');
insert into employee (id, username, password) values (18, 'tjankovich', 'yELDgLvAt5');
insert into employee (id, username, password) values (19, 'rgodlemani', 'NUs7TDQi');
insert into employee (id, username, password) values (20, 'cstrutzj', 'kwLQzv9pda93');
insert into employee (id, username, password) values (21, 'lchumleyk', 'K6LjOwsurD');
insert into employee (id, username, password) values (22, 'ochinnockl', '4ESwADvfYm');
insert into employee (id, username, password) values (23, 'ahyamm', 'YTR3JN');
insert into employee (id, username, password) values (24, 'sgoatmann', 'XTHbYR0OPep');
insert into employee (id, username, password) values (25, 'adensello', 'HDh022F');
insert into employee (id, username, password) values (26, 'dakkerp', 'unNYx69rjO9K');
insert into employee (id, username, password) values (27, 'gbesteq', 'DlGuDScUEP6');
insert into employee (id, username, password) values (28, 'dlassellsr', 't0MH6KSCWn');
insert into employee (id, username, password) values (29, 'gpackhams', 'qdEcUAMXmXnk');
insert into employee (id, username, password) values (30, 'avaldert', 'QIYcU6cN4');
insert into employee (id, username, password) values (31, 'lfiennesu', 'hhHO20At');
insert into employee (id, username, password) values (32, 'clemariev', 'TUDgCNE8OMza');
insert into employee (id, username, password) values (33, 'btongew', 'wBdhp3EU0');
insert into employee (id, username, password) values (34, 'mbridgestockx', '0q0Me7082iOa');
insert into employee (id, username, password) values (35, 'lcontiy', 'JQZjVUluJ');
insert into employee (id, username, password) values (36, 'lsaintsburyz', 'vmvLbvTP');
insert into employee (id, username, password) values (37, 'dmariner10', 'eyzen5x8YVxk');
insert into employee (id, username, password) values (38, 'jatterbury11', 'WtCGyGmR');
insert into employee (id, username, password) values (39, 'gmcgraith12', '9JQQNle1v');
insert into employee (id, username, password) values (40, 'djeffery13', 'WpHxQ6');
insert into employee (id, username, password) values (41, 'ranespie14', 'giyjzzQ');
insert into employee (id, username, password) values (42, 'sgergus15', 'H49RKN71z');
insert into employee (id, username, password) values (43, 'kgilstin16', 'S3WAbcwAz');
insert into employee (id, username, password) values (44, 'vasquith17', 'cSgM1dsnjtzK');
insert into employee (id, username, password) values (45, 'ciannuzzi18', 'NuL2TjhwxRZ');
insert into employee (id, username, password) values (46, 'mfilipyev19', 'luwOrKk');
insert into employee (id, username, password) values (47, 'ebelfitt1a', 'XDkkQC44Zc');
insert into employee (id, username, password) values (48, 'aseldon1b', 'rKXRf5A3T');
insert into employee (id, username, password) values (49, 'btapsfield1c', 'KsLZUmslg1W');
insert into employee (id, username, password) values (50, 'rkores1d', 'ocl9lx');
insert into employee (id, username, password) values (51, 'gbirt1e', 'C0J7Ru');
insert into employee (id, username, password) values (52, 'mdsouza1f', '8slKDMcvct');
insert into employee (id, username, password) values (53, 'lflann1g', 'xKkLhWq11');
insert into employee (id, username, password) values (54, 'cpeakman1h', '72i2qFMOI');
insert into employee (id, username, password) values (55, 'bgillibrand1i', '2gSdTZ');
insert into employee (id, username, password) values (56, 'ajirieck1j', 'TJlZiHycJ');
insert into employee (id, username, password) values (57, 'pshelvey1k', 'q1zdFjPITpm');
insert into employee (id, username, password) values (58, 'rivanisov1l', 'Y9NSQZJ');
insert into employee (id, username, password) values (59, 'pbirchenhead1m', '9pYUR38l');
insert into employee (id, username, password) values (60, 'clabarre1n', 'HtdK9n');
insert into employee (id, username, password) values (61, 'vbrands1o', 'rljOgw5');
insert into employee (id, username, password) values (62, 'mferris1p', 'oX6lULk6W');
insert into employee (id, username, password) values (63, 'apopov1q', 'XU9AVwnVheo');
insert into employee (id, username, password) values (64, 'swignall1r', '38vpMHRfNks');
insert into employee (id, username, password) values (65, 'cnodes1s', 'tWuVyqtB');
insert into employee (id, username, password) values (66, 'rgenese1t', 'D0ROsChmh9i');
insert into employee (id, username, password) values (67, 'hsaph1u', 'C5VAvNu5Ii3');
insert into employee (id, username, password) values (68, 'rbritten1v', 'CHz1vVM');
insert into employee (id, username, password) values (69, 'tkayes1w', '3GTz5F');
insert into employee (id, username, password) values (70, 'rgertz1x', 'UHzoALjHWK8n');
insert into employee (id, username, password) values (71, 'bbasso1y', '7a9fb4mH');
insert into employee (id, username, password) values (72, 'sfewings1z', 'lUZFLq7');
insert into employee (id, username, password) values (73, 'rtrevascus20', 'EiZ5Q1l04');
insert into employee (id, username, password) values (74, 'dflanagan21', '5YTzbhi4OmpY');
insert into employee (id, username, password) values (75, 'mskeemor22', 'fds02AhU');
insert into employee (id, username, password) values (76, 'vjohl23', 'P2G2Z2xWhUd');
insert into employee (id, username, password) values (77, 'mcharnick24', 'GlvaAywv');
insert into employee (id, username, password) values (78, 'lmerrigans25', 'cerFVaEAe5Ks');
insert into employee (id, username, password) values (79, 'stoms26', 'Qtcvx0');
insert into employee (id, username, password) values (80, 'tdalwis27', '2cqVUycy5');
insert into employee (id, username, password) values (81, 'ddevanny28', 'QCfCBT');
insert into employee (id, username, password) values (82, 'efarquarson29', 'ONrxPMainam');
insert into employee (id, username, password) values (83, 'jhirsch2a', 'eAYGrCq');
insert into employee (id, username, password) values (84, 'nfallanche2b', 'BObrK5');
insert into employee (id, username, password) values (85, 'awhordley2c', 'iFU3mpzjC4Xn');
insert into employee (id, username, password) values (86, 'ddumper2d', 'f0ZBS74tn');
insert into employee (id, username, password) values (87, 'cjeannet2e', 'rktP1K1a');
insert into employee (id, username, password) values (88, 'clevick2f', 'eOHLRBNNN');
insert into employee (id, username, password) values (89, 'ehulls2g', '9hodjr7HFi');
insert into employee (id, username, password) values (90, 'epoge2h', 'xdNWJLyqv');
insert into employee (id, username, password) values (91, 'efilipchikov2i', 'fYaIwgdVyBy');
insert into employee (id, username, password) values (92, 'ndupey2j', 'yGy55R7hY');
insert into employee (id, username, password) values (93, 'eluchelli2k', 'YvEiZ2KQUV');
insert into employee (id, username, password) values (94, 'ashorton2l', 'qH5CS5NLb2L');
insert into employee (id, username, password) values (95, 'nstuffins2m', 'kqBC6mNKi');
insert into employee (id, username, password) values (96, 'kkubes2n', 'kR1rmfN');
insert into employee (id, username, password) values (97, 'lwinton2o', '3m10HuXwfb');
insert into employee (id, username, password) values (98, 'lhazleton2p', 'S4sg5gdW1Z');
insert into employee (id, username, password) values (99, 'cgoolden2q', 'mhpf5Wn44');
insert into employee (id, username, password) values (100, 'ldemsey2r', 'JWlhXribhGO');
insert into employee (id, username, password) values (101, 'sgiorio2s', 'CDzRM3miIj');
insert into employee (id, username, password) values (102, 'elabb2t', '2x6Q5yoD5');
insert into employee (id, username, password) values (103, 'cridings2u', 'keZkif5i');
insert into employee (id, username, password) values (104, 'amunton2v', 'sSlFXS3k21');
insert into employee (id, username, password) values (105, 'lhinz2w', 'WuyzWAVEZ');
insert into employee (id, username, password) values (106, 'nlomansey2x', 'c2uujm6');
insert into employee (id, username, password) values (107, 'raveray2y', 'jmNJya2');
insert into employee (id, username, password) values (108, 'clardeur2z', '7AsarNdCLv');
insert into employee (id, username, password) values (109, 'tpicheford30', 'zufeRY');
insert into employee (id, username, password) values (110, 'mbrussell31', 'Xxxl7ZtNO5tN');
insert into employee (id, username, password) values (111, 'acornely32', 'pynyGAeKwIp3');
insert into employee (id, username, password) values (112, 'fkestle33', 'fSZnp42uCva');
insert into employee (id, username, password) values (113, 'jbeacon34', 'YHqrJTY0Zb');
insert into employee (id, username, password) values (114, 'jalwen35', 'HXV4Z4Vinn');
insert into employee (id, username, password) values (115, 'kriehm36', 'GN2EaqhBXh');
insert into employee (id, username, password) values (116, 'yboyen37', 'BPxzdanL2');
insert into employee (id, username, password) values (117, 'ewestmerland38', 'M5II3l');
insert into employee (id, username, password) values (118, 'gstubbe39', 'MrixAAVCdM');
insert into employee (id, username, password) values (119, 'cmoyes3a', 'QQK3MK5twFI7');
insert into employee (id, username, password) values (120, 'lmarchington3b', 'I5p94J');
insert into employee (id, username, password) values (121, 'ihaacker3c', 'I3y5YaKV');
insert into employee (id, username, password) values (122, 'epinxton3d', 'vKkjtrM');
insert into employee (id, username, password) values (123, 'kdamarell3e', 'nBH9QijGEDv');
insert into employee (id, username, password) values (124, 'ffouracres3f', 'cYFrX1raA47b');
insert into employee (id, username, password) values (125, 'svisco3g', 'o7l0mm6Sg');
insert into employee (id, username, password) values (126, 'grupprecht3h', 'F6d7T6DGMRp9');
insert into employee (id, username, password) values (127, 'srust3i', '04J9d94N6kr');
insert into employee (id, username, password) values (128, 'ggoard3j', '26XtPXCF');
insert into employee (id, username, password) values (129, 'cdict3k', 'RSGlmYM');
insert into employee (id, username, password) values (130, 'jmontgomery3l', 'GmPfgq');
insert into employee (id, username, password) values (131, 'kwetherill3m', 'UlxLdiW2FtW');
insert into employee (id, username, password) values (132, 'rdispencer3n', 'eA8s59');
insert into employee (id, username, password) values (133, 'mdenniston3o', '6MXqQcd0u9W');
insert into employee (id, username, password) values (134, 'ctiplady3p', 'Jc0zPANPJCYo');
insert into employee (id, username, password) values (135, 'hjeays3q', '6nqpmRQ');
insert into employee (id, username, password) values (136, 'hmarini3r', 'NoU6llHHkp');
insert into employee (id, username, password) values (137, 'ybottby3s', 'Efm2xg1');
insert into employee (id, username, password) values (138, 'acritoph3t', 'byrpkKjmLWy8');
insert into employee (id, username, password) values (139, 'amaylam3u', 'sCi2fPW');
insert into employee (id, username, password) values (140, 'wsokell3v', 'G1HexlKovqld');
insert into employee (id, username, password) values (141, 'ttatton3w', 'kXpHekozeN');
insert into employee (id, username, password) values (142, 'ctait3x', 'tMYG4T');
insert into employee (id, username, password) values (143, 'abingham3y', 'cqSxE8mC5U');
insert into employee (id, username, password) values (144, 'iridger3z', 'ZjxJ9Ir5yUjz');
insert into employee (id, username, password) values (145, 'broddie40', 'fv6Ktmxs7Xv');
insert into employee (id, username, password) values (146, 'amateuszczyk41', 'xeJcsM');
insert into employee (id, username, password) values (147, 'salbert42', 'UHyD6RjV');
insert into employee (id, username, password) values (148, 'gmix43', 'OQMrpv2');
insert into employee (id, username, password) values (149, 'bsillick44', '2pmoTqx');
insert into employee (id, username, password) values (150, 'hzorzi45', 'i32DYL');
insert into employee (id, username, password) values (151, 'mgoult46', 'C4UYbSU');
insert into employee (id, username, password) values (152, 'lworthington47', '3K9rQN3g');
insert into employee (id, username, password) values (153, 'gbernat48', 'v5A54zo3xQ');
insert into employee (id, username, password) values (154, 'iakroyd49', '0mYNihe');
insert into employee (id, username, password) values (155, 'sordelt4a', 'Ew07uhEdE');
insert into employee (id, username, password) values (156, 'dmortlock4b', 'gV9J54hGv27Y');
insert into employee (id, username, password) values (157, 'ebussey4c', 'hslnQ7H');
insert into employee (id, username, password) values (158, 'bcallister4d', '2A71OD8');
insert into employee (id, username, password) values (159, 'ceble4e', 'q83elq6fk');
insert into employee (id, username, password) values (160, 'bclapson4f', 'ST7Pf94Bqz');
insert into employee (id, username, password) values (161, 'scumberpatch4g', '7byvwd265Ol');
insert into employee (id, username, password) values (162, 'vkeele4h', 'df8Jghe3NKMU');
insert into employee (id, username, password) values (163, 'dchiechio4i', 'RkqINjhd0TQ');
insert into employee (id, username, password) values (164, 'wdavern4j', 'eTJdxF7taoG3');
insert into employee (id, username, password) values (165, 'mgerler4k', 'D6a2w5OEyNlb');
insert into employee (id, username, password) values (166, 'hblesli4l', 'cQWIHp2BO');
insert into employee (id, username, password) values (167, 'amarquis4m', 'rHBKEq');
insert into employee (id, username, password) values (168, 'mchancelier4n', 'EMVGGfSM2Ah');
insert into employee (id, username, password) values (169, 'akeig4o', '1xQ26V');
insert into employee (id, username, password) values (170, 'sbarbour4p', 'dDmeccJZ1j0');
insert into employee (id, username, password) values (171, 'tdulton4q', 'regmas');
insert into employee (id, username, password) values (172, 'sbridgland4r', 'UYg7mt');
insert into employee (id, username, password) values (173, 'swatt4s', 'YKN8wOB');
insert into employee (id, username, password) values (174, 'cmaypother4t', '03FSDz');
insert into employee (id, username, password) values (175, 'ddeighan4u', 'nbJINpcaqf');
insert into employee (id, username, password) values (176, 'hmayell4v', 'vITKfq');
insert into employee (id, username, password) values (177, 'cjannasch4w', 'xLRGfq');
insert into employee (id, username, password) values (178, 'hvanarsdalen4x', 'kitcxkn');
insert into employee (id, username, password) values (179, 'rclogg4y', 'XbMhoz7zFu3D');
insert into employee (id, username, password) values (180, 'mblackhurst4z', 'UVqWwr9poK');
insert into employee (id, username, password) values (181, 'dburndred50', '3YGn8XoixA');
insert into employee (id, username, password) values (182, 'amughal51', 'crhY5QA2');
insert into employee (id, username, password) values (183, 'oleinthall52', 'QPGhyD');
insert into employee (id, username, password) values (184, 'htincey53', 'gqzWR5GZ');
insert into employee (id, username, password) values (185, 'skluger54', 'vXzejZ');
insert into employee (id, username, password) values (186, 'sborchardt55', 'r69Mqde8uyJp');
insert into employee (id, username, password) values (187, 'dolahy56', '4FT1ww');
insert into employee (id, username, password) values (188, 'knias57', 'oCZ4sDny');
insert into employee (id, username, password) values (189, 'alovart58', 'O9NJOiby');
insert into employee (id, username, password) values (190, 'fvaskin59', 'kwIHgpeeJr');
insert into employee (id, username, password) values (191, 'tchieze5a', 'iSQaGDkT');
insert into employee (id, username, password) values (192, 'gwinterscale5b', 'Nei9iSE');
insert into employee (id, username, password) values (193, 'vjean5c', 'csfXNvL');
insert into employee (id, username, password) values (194, 'rmccaw5d', 'z2a73GuOPso');
insert into employee (id, username, password) values (195, 'doshields5e', 'dvAjEG6zfRLe');
insert into employee (id, username, password) values (196, 'rminister5f', '4o7zA4GbtOwr');
insert into employee (id, username, password) values (197, 'mmanilove5g', 'Vu7g9RQer');
insert into employee (id, username, password) values (198, 'bgriss5h', 'G8XAmBIGMysF');
insert into employee (id, username, password) values (199, 'khadleigh5i', 'HSYFH0');
insert into employee (id, username, password) values (200, 'cede5j', 'Rtmi6EsepPXF');
insert into employee (id, username, password) values (201, 'dodoireidh5k', 'E9Ob6Z');
insert into employee (id, username, password) values (202, 'csellick5l', 'dARB84BPz2R');
insert into employee (id, username, password) values (203, 'mgercken5m', 'G1KGBBt');
insert into employee (id, username, password) values (204, 'mmoulding5n', 'jOXAdQtaU');
insert into employee (id, username, password) values (205, 'akier5o', 'kKAmGVNclaJs');
insert into employee (id, username, password) values (206, 'sseyers5p', 'zDTXlUlD6E');
insert into employee (id, username, password) values (207, 'nganforthe5q', 'DvSL8jks');
insert into employee (id, username, password) values (208, 'byoung5r', 'ZehVjTZWo');
insert into employee (id, username, password) values (209, 'amyhill5s', 'GGSspjtPAd3g');
insert into employee (id, username, password) values (210, 'aslot5t', 'g0oIjMsrxqKf');
insert into employee (id, username, password) values (211, 'fwynett5u', '1HeR2Hshj');
insert into employee (id, username, password) values (212, 'wwaterdrinker5v', 'PRetUziFgaE1');
insert into employee (id, username, password) values (213, 'pmishaw5w', '51i4Wc0Ycq');
insert into employee (id, username, password) values (214, 'dmcaline5x', 'Q5ZaBg');
insert into employee (id, username, password) values (215, 'fnorcutt5y', 'XCtp2f');
insert into employee (id, username, password) values (216, 'zbarhem5z', 'Y6ZX2e');
insert into employee (id, username, password) values (217, 'afannin60', 'mE4QN5yEJ');
insert into employee (id, username, password) values (218, 'agotthard61', 'yHVJTLL4fm');
insert into employee (id, username, password) values (219, 'gpomphrey62', 'gvFLWXx0t0sG');
insert into employee (id, username, password) values (220, 'iworks63', '96vQ6QOut0');
insert into employee (id, username, password) values (221, 'stomlett64', 'N7cZb7ak2vE');
insert into employee (id, username, password) values (222, 'mbosward65', 'vnOQQkHEfJE');
insert into employee (id, username, password) values (223, 'wolehane66', 'xUXZyC4Op2yP');
insert into employee (id, username, password) values (224, 'dkellart67', 'dX3EBX5B6uS');

insert into customer (id, username, password) values (1, 'wdefreyne0', '99CYaCvIa');
insert into customer (id, username, password) values (2, 'meckley1', 'jXZyKuNALAZi');
insert into customer (id, username, password) values (3, 'dperrie2', 'Oekvx64yUXJ');
insert into customer (id, username, password) values (4, 'lclevely3', 'AUwbdGpNYoV');
insert into customer (id, username, password) values (5, 'hcrosfield4', 'DgXDFi1');
insert into customer (id, username, password) values (6, 'cmeller5', 'u6w4mwo3u');
insert into customer (id, username, password) values (7, 'oblackledge6', 'SeGfjKLd');
insert into customer (id, username, password) values (8, 'smynard7', 'MduZuVKuuY');
insert into customer (id, username, password) values (9, 'kwiggall8', '1eIVU3LQRt');
insert into customer (id, username, password) values (10, 'kbartlomiejczyk9', 'SFfyqDYDBcg');
insert into customer (id, username, password) values (11, 'krappaporta', 'dx4WzN9Jb3bv');
insert into customer (id, username, password) values (12, 'vsartenb', 'zlmPI23z');
insert into customer (id, username, password) values (13, 'kcobonc', 'fTZGweWux');
insert into customer (id, username, password) values (14, 'dreimersd', 'U1E6ovqf8');
insert into customer (id, username, password) values (15, 'amenate', 'Rk2Is8');
insert into customer (id, username, password) values (16, 'lfreenf', 'Wcpu1Qck7Af');
insert into customer (id, username, password) values (17, 'vkillingsworthg', 'km1oNoS');
insert into customer (id, username, password) values (18, 'jpavolinih', '1jSRm4o');
insert into customer (id, username, password) values (19, 'godoughertyi', 'PpGinFZ8');
insert into customer (id, username, password) values (20, 'tbeej', 'H1RY5CGiXjJA');
insert into customer (id, username, password) values (21, 'ccurlisk', 'sOFlKW6FL');
insert into customer (id, username, password) values (22, 'sdonnel', 'Qh2dw2j');
insert into customer (id, username, password) values (23, 'ehostonm', '7qChTe8Ab0pR');
insert into customer (id, username, password) values (24, 'wkinign', '3aSX2f');
insert into customer (id, username, password) values (25, 'bskupinskio', '7no2PXcf');
insert into customer (id, username, password) values (26, 'ssewardsp', 'E65OmqFfNWHa');
insert into customer (id, username, password) values (27, 'deastopeq', 'vLcDLEWLvKY');
insert into customer (id, username, password) values (28, 'cbacker', 'Vs6rIL0EN2');
insert into customer (id, username, password) values (29, 'fferronels', 'KXNdjyjsIFPE');
insert into customer (id, username, password) values (30, 'vgwilliamst', 'RPpYvoLQyr');
insert into customer (id, username, password) values (31, 'aradbandu', 'BbxJLqa');
insert into customer (id, username, password) values (32, 'wdorosariov', '90XGrBA');
insert into customer (id, username, password) values (33, 'jpointsw', 'lRvo6CG3ynSj');
insert into customer (id, username, password) values (34, 'dlilleymanx', 'ntkeFtx4unf');
insert into customer (id, username, password) values (35, 'dslatchery', '3buRC8A');
insert into customer (id, username, password) values (36, 'gyoz', 'Knt8XqRrRc');
insert into customer (id, username, password) values (37, 'ogerleit10', 'Rn8Q1Gvhk');
insert into customer (id, username, password) values (38, 'cscothern11', '3iya8U');
insert into customer (id, username, password) values (39, 'dbony12', 'YtOoZfgBuc7c');
insert into customer (id, username, password) values (40, 'jricardot13', 'fX2uJpL');
insert into customer (id, username, password) values (41, 'ejurasz14', 'dOKGyv');
insert into customer (id, username, password) values (42, 'abutson15', 'Le4ZlooXA');
insert into customer (id, username, password) values (43, 'glaughton16', 'fXSPAHETyc');
insert into customer (id, username, password) values (44, 'bgammill17', 'ETYiGl4aHjyn');
insert into customer (id, username, password) values (45, 'smedforth18', 'YYhZmAuoDURP');
insert into customer (id, username, password) values (46, 'aludovici19', '7DjZ8s');
insert into customer (id, username, password) values (47, 'askerratt1a', 'E4U9HfO');
insert into customer (id, username, password) values (48, 'ckenright1b', '9p5Ec6siTEY');
insert into customer (id, username, password) values (49, 'cswedeland1c', '31q8kXTR7');
insert into customer (id, username, password) values (50, 'cstancliffe1d', 'plflPo');
insert into customer (id, username, password) values (51, 'rhawkwood1e', '6uj9HP9i0BaT');
insert into customer (id, username, password) values (52, 'cmateos1f', 'fGohBszE9');
insert into customer (id, username, password) values (53, 'afleetwood1g', 'acP9KMnp9');
insert into customer (id, username, password) values (54, 'abeeke1h', 'yCbxL1k1qX16');
insert into customer (id, username, password) values (55, 'tdurn1i', 'eWZrVyaDiJ');
insert into customer (id, username, password) values (56, 'vklulicek1j', 'zEVnSHJ7');
insert into customer (id, username, password) values (57, 'dlarraway1k', 'zdc0f9Kanf');
insert into customer (id, username, password) values (58, 'enaisby1l', 'y0fgaycJ');
insert into customer (id, username, password) values (59, 'ebembrigg1m', 'hfAboIOp');
insert into customer (id, username, password) values (60, 'rbau1n', 'AIYSf4qEbCY');
insert into customer (id, username, password) values (61, 'ndalyell1o', 'Aqzrp3B1');
insert into customer (id, username, password) values (62, 'lhadigate1p', 'jqSA2kGUUGh');
insert into customer (id, username, password) values (63, 'iastill1q', 'UOlBf5g');
insert into customer (id, username, password) values (64, 'trummings1r', '0G0HLCaqhyaj');
insert into customer (id, username, password) values (65, 'bgori1s', 'BmBPWn');
insert into customer (id, username, password) values (66, 'mmeiklam1t', 'wDkCdUE9');
insert into customer (id, username, password) values (67, 'rjirzik1u', 'NkZTgglsu9QF');
insert into customer (id, username, password) values (68, 'ytavinor1v', 'OBlcXfq');
insert into customer (id, username, password) values (69, 'aciccetti1w', 'IUs7Djxsn');
insert into customer (id, username, password) values (70, 'lmonteith1x', 'aojehFs6SMlA');
insert into customer (id, username, password) values (71, 'fbourke1y', '5bjcam0cMvk5');
insert into customer (id, username, password) values (72, 'hgioan1z', 'F8YL4KNToYPO');
insert into customer (id, username, password) values (73, 'hlympany20', 'jjYpu5w5D');
insert into customer (id, username, password) values (74, 'cthorntondewhirst21', 'XzHbYLl');
insert into customer (id, username, password) values (75, 'clesek22', 'RjhJoCYi25');
insert into customer (id, username, password) values (76, 'pbraker23', 'LJSPcy');
insert into customer (id, username, password) values (77, 'edemicoli24', 'GbpGKujQ7L6l');
insert into customer (id, username, password) values (78, 'msandbach25', 'GGPxhp2ubRBv');
insert into customer (id, username, password) values (79, 'mhannah26', '5sL78Y4xJA');
insert into customer (id, username, password) values (80, 'callwright27', 'FmGKkOAj');
insert into customer (id, username, password) values (81, 'rgahagan28', 'jJXWpz2rq');
insert into customer (id, username, password) values (82, 'rrolph29', 'UhHpWEQr');
insert into customer (id, username, password) values (83, 'emunnings2a', '3BmQtS2QfH');
insert into customer (id, username, password) values (84, 'ecrittal2b', 'JIc4Mb9r');
insert into customer (id, username, password) values (85, 'lbranwhite2c', 'G1YpxD1Q');
insert into customer (id, username, password) values (86, 'tcoverdill2d', 'RspA5XB7');
insert into customer (id, username, password) values (87, 'macutt2e', '88nPtWqhcLR');
insert into customer (id, username, password) values (88, 'dborrell2f', 'IGwPazlZ');
insert into customer (id, username, password) values (89, 'babella2g', 'GMYPcI4CL0');
insert into customer (id, username, password) values (90, 'cskip2h', 'bc4PBpo');
insert into customer (id, username, password) values (91, 'mlambert2i', 'jd4KhVEg');
insert into customer (id, username, password) values (92, 'jhazelden2j', '5DZITDY');
insert into customer (id, username, password) values (93, 'gbugbee2k', 'hodp4Bk');
insert into customer (id, username, password) values (94, 'mfeldmann2l', 'vpSyT6dS');
insert into customer (id, username, password) values (95, 'rblackmore2m', 'PhEOvUrf');
insert into customer (id, username, password) values (96, 'klabrow2n', '5MeySoL');
insert into customer (id, username, password) values (97, 'gheinig2o', 'xnJFKpTvUzI');
insert into customer (id, username, password) values (98, 'lbilt2p', 'L9bGgP9sxi');
insert into customer (id, username, password) values (99, 'vharrild2q', 'wrFUG1');
insert into customer (id, username, password) values (100, 'mlates2r', '52uM4IVVLmH');
insert into customer (id, username, password) values (101, 'keasum2s', 'w9ob2giK');
insert into customer (id, username, password) values (102, 'bfritschmann2t', 'UOJkP66n');
insert into customer (id, username, password) values (103, 'wmabbot2u', '882h5JmJg4');
insert into customer (id, username, password) values (104, 'btrimnell2v', 'HxRTMrgHZ');
insert into customer (id, username, password) values (105, 'ematthiesen2w', 'dGngTKL');
insert into customer (id, username, password) values (106, 'gelcott2x', 'HvjApf8hf');
insert into customer (id, username, password) values (107, 'jwither2y', 'tBC2I1n5m');
insert into customer (id, username, password) values (108, 'bsheaber2z', 'dE8dFGw4zKq');
insert into customer (id, username, password) values (109, 'ccranstone30', 'CwsSOjRovp');
insert into customer (id, username, password) values (110, 'btulleth31', 'cEd4Z6bMnwm');
insert into customer (id, username, password) values (111, 'ptubritt32', 'dK6hU3');
insert into customer (id, username, password) values (112, 'shollingsby33', '30tqMa');
insert into customer (id, username, password) values (113, 'drathke34', 'KXuyy6slUbI');
insert into customer (id, username, password) values (114, 'gwoodland35', 'xvC6TFlMQ');
insert into customer (id, username, password) values (115, 'rmabbe36', '4sOKgIS');
insert into customer (id, username, password) values (116, 'bholdren37', 'kNasysZV45');
insert into customer (id, username, password) values (117, 'jmears38', 'SNizTrxW');
insert into customer (id, username, password) values (118, 'hkures39', '6XCR5tUwjh');
insert into customer (id, username, password) values (119, 'asebright3a', '6izsVGwN');
insert into customer (id, username, password) values (120, 'tcoffee3b', 'PYASEJI');
insert into customer (id, username, password) values (121, 'sgrundey3c', 'KvPdUchesU');
insert into customer (id, username, password) values (122, 'aling3d', 'Ej5gdLNPgN');
insert into customer (id, username, password) values (123, 'pbatter3e', 'XyIF6bvwjh5D');
insert into customer (id, username, password) values (124, 'jtredger3f', '5gh8HTf');
insert into customer (id, username, password) values (125, 'acleland3g', 'zsiQLHAl');
insert into customer (id, username, password) values (126, 'ofalkner3h', 'c8udTnz');
insert into customer (id, username, password) values (127, 'mocaherny3i', 'Q4aflG');
insert into customer (id, username, password) values (128, 'akanzler3j', '01qm3O6');
insert into customer (id, username, password) values (129, 'sbiagini3k', '0gLOgUkvL');
insert into customer (id, username, password) values (130, 'rgilardengo3l', 'RHPrkdltQs');
insert into customer (id, username, password) values (131, 'prebanks3m', 'QuZgrvjfNV4t');
insert into customer (id, username, password) values (132, 'mjorcke3n', 'graDg6aTkeBZ');
insert into customer (id, username, password) values (133, 'tbelton3o', 'DPl7vGA');
insert into customer (id, username, password) values (134, 'jrackham3p', 'fFYaqojaNWK');
insert into customer (id, username, password) values (135, 'mbancroft3q', 'rPBa05V');
insert into customer (id, username, password) values (136, 'bedeler3r', 'dtckFKzRUATf');
insert into customer (id, username, password) values (137, 'elongdon3s', 'FDbDG3');
insert into customer (id, username, password) values (138, 'atuxell3t', 'btO0Lb');
insert into customer (id, username, password) values (139, 'lsmewin3u', 'q2txqD2jQee');
insert into customer (id, username, password) values (140, 'jrostern3v', 'xhQLy72jssO');
insert into customer (id, username, password) values (141, 'emacauley3w', 'cDLJwYcFVT');
insert into customer (id, username, password) values (142, 'bgremane3x', 'vKmxl9d3');
insert into customer (id, username, password) values (143, 'fstirtle3y', 'nO1CZk0Q6');
insert into customer (id, username, password) values (144, 'cenever3z', 'HIdpclW');
insert into customer (id, username, password) values (145, 'ggeddes40', 'wvwVDySfu');
insert into customer (id, username, password) values (146, 'strye41', 'sNeAWNPzC6Pw');
insert into customer (id, username, password) values (147, 'jstopps42', 'PNseax8js');
insert into customer (id, username, password) values (148, 'dstarcks43', 'SorlFbN1pYxm');
insert into customer (id, username, password) values (149, 'tcrookston44', 'tCbIhZH');
insert into customer (id, username, password) values (150, 'goffin45', 'WmAHhWWjH');
insert into customer (id, username, password) values (151, 'abirrane46', 'PuYOjHCHB');
insert into customer (id, username, password) values (152, 'rthrossell47', 'FnYNjt0s');
insert into customer (id, username, password) values (153, 'pstainsby48', 'U8Srjq87plR');
insert into customer (id, username, password) values (154, 'sdinsale49', 'AGRln5wK1k');
insert into customer (id, username, password) values (155, 'lkollatsch4a', 'z3JYJoT');
insert into customer (id, username, password) values (156, 'gquartly4b', '99mRzWTRm');
insert into customer (id, username, password) values (157, 'hbusk4c', 'H0ex3f0');
insert into customer (id, username, password) values (158, 'ktailour4d', 'gF0bf7x2');
insert into customer (id, username, password) values (159, 'gdrissell4e', 'VoRQWAXZyNi');
insert into customer (id, username, password) values (160, 'doldmeadow4f', 'nQnLWOYe');
insert into customer (id, username, password) values (161, 'smctrustam4g', 'Y7yPnk');
insert into customer (id, username, password) values (162, 'ttandy4h', 'IxKDBLNX3cy0');
insert into customer (id, username, password) values (163, 'oearland4i', '5Mlpyd');
insert into customer (id, username, password) values (164, 'hgoatman4j', '7UzeA5RdM');
insert into customer (id, username, password) values (165, 'fbirkin4k', 'dAFmqGmSHY');
insert into customer (id, username, password) values (166, 'ngollin4l', 'kMpbcwk');
insert into customer (id, username, password) values (167, 'bfeasby4m', 'gm7BMD');
insert into customer (id, username, password) values (168, 'lbecerro4n', 'TRtaJJ9J');
insert into customer (id, username, password) values (169, 'kmerchant4o', '6ysRB7');
insert into customer (id, username, password) values (170, 'arhys4p', 'ZtqvDZ');
insert into customer (id, username, password) values (171, 'swoodcock4q', 'XSGFrvpM3r');
insert into customer (id, username, password) values (172, 'jpeasgood4r', 'Ka8PTqki0y');
insert into customer (id, username, password) values (173, 'mvenour4s', 'EuagUZDsa8S');
insert into customer (id, username, password) values (174, 'gplummer4t', 'rjh6PWVuFd');
insert into customer (id, username, password) values (175, 'obranton4u', 'V8cGYJkeX');
insert into customer (id, username, password) values (176, 'eurvoy4v', 'iSjqq13vMxZT');
insert into customer (id, username, password) values (177, 'cbeetham4w', 'pBCqGJ');
insert into customer (id, username, password) values (178, 'bhegley4x', 'w6kD5CTS');
insert into customer (id, username, password) values (179, 'mcecely4y', 'tfMvC8HpH');
insert into customer (id, username, password) values (180, 'gtettersell4z', '5SohmmKxBf');
insert into customer (id, username, password) values (181, 'mpull50', 'xpghZZZ2m');
insert into customer (id, username, password) values (182, 'jdeering51', '0rwANJH');
insert into customer (id, username, password) values (183, 'cfairpo52', 'BpqSGf');
insert into customer (id, username, password) values (184, 'mblucher53', 'ktwZCdjBgv7');
insert into customer (id, username, password) values (185, 'dweekland54', 'wva7ao');
insert into customer (id, username, password) values (186, 'jdearell55', 'BBlaG4tDAE');
insert into customer (id, username, password) values (187, 'gantoniottii56', 'JqjEpt');
insert into customer (id, username, password) values (188, 'jjertz57', 'IZmWvU0E');
insert into customer (id, username, password) values (189, 'kgaskoin58', '8HKYCRc');
insert into customer (id, username, password) values (190, 'jemms59', '5K3aa7xfmMDe');
insert into customer (id, username, password) values (191, 'emaffezzoli5a', 'M4i5Wo');
insert into customer (id, username, password) values (192, 'gwoollett5b', 'QTQgLY');
insert into customer (id, username, password) values (193, 'nbridat5c', 'PwvKAzQurz');
insert into customer (id, username, password) values (194, 'aharms5d', '96gKWB');
insert into customer (id, username, password) values (195, 'agiacaponi5e', 'CwjFaqagwb');
insert into customer (id, username, password) values (196, 'lraithbie5f', 'Gt3CnZSKZWZl');
insert into customer (id, username, password) values (197, 'agraber5g', '8UZytj0H');
insert into customer (id, username, password) values (198, 'ydonner5h', 'UFA8iTu0e5yl');
insert into customer (id, username, password) values (199, 'abeverage5i', 'zAcl6HsfhK');
insert into customer (id, username, password) values (200, 'cdo5j', '9ocOJfsa');
insert into customer (id, username, password) values (201, 'ncohen5k', '3u2tyAhRoHc');
insert into customer (id, username, password) values (202, 'nvandrill5l', 'fU6ek14k');
insert into customer (id, username, password) values (203, 'fborrel5m', 'WdcDFiUshpj');
insert into customer (id, username, password) values (204, 'sberick5n', 'KvUIk0Ksk');
insert into customer (id, username, password) values (205, 'eferrotti5o', 'VuG8OZB');
insert into customer (id, username, password) values (206, 'jnorville5p', 'zmEEk5');
insert into customer (id, username, password) values (207, 'bparren5q', 'Vp4FjrNNT');
insert into customer (id, username, password) values (208, 'bbingall5r', 'qstEciA0oP6n');
insert into customer (id, username, password) values (209, 'lallom5s', '7dYTMy0VS');
insert into customer (id, username, password) values (210, 'dgerber5t', 'EMRBzCZJU');
insert into customer (id, username, password) values (211, 'kpownall5u', 'U9AJkdPjw');
insert into customer (id, username, password) values (212, 'prispin5v', 'D7LI0W');
insert into customer (id, username, password) values (213, 'jstivers5w', 'slaq4GAqL3kc');
insert into customer (id, username, password) values (214, 'cvinker5x', 'NlUWBElnR');
insert into customer (id, username, password) values (215, 'mrodnight5y', 'gkHrVsc');
insert into customer (id, username, password) values (216, 'jclee5z', 'RX19SutvGb');
insert into customer (id, username, password) values (217, 'mhise60', '94r61w');
insert into customer (id, username, password) values (218, 'scorking61', 'AWWxEajago');
insert into customer (id, username, password) values (219, 'jreadwood62', 'C8OdpGGW');
insert into customer (id, username, password) values (220, 'ilowder63', 'V9NQaCje');
insert into customer (id, username, password) values (221, 'pjurczyk64', 'DxteHAxQWni');
insert into customer (id, username, password) values (222, 'mgentsch65', 'U7omusSq87');
insert into customer (id, username, password) values (223, 'dcompson66', 'JD0NNBY9QV');
insert into customer (id, username, password) values (224, 'ariggoll67', '3TD67d');
insert into customer (id, username, password) values (225, 'msaurat68', 'jgBSxajuY8');
insert into customer (id, username, password) values (226, 'vmahaddie69', 'XiJpFyIO7jQ');
insert into customer (id, username, password) values (227, 'smacgebenay6a', 'S0opn4Qd');
insert into customer (id, username, password) values (228, 'zbalmer6b', 'OlVaTngs');
insert into customer (id, username, password) values (229, 'sbarabisch6c', 'B5IRPbZsNKY');
insert into customer (id, username, password) values (230, 'cgentiry6d', 'PqhEeRVYNm');
insert into customer (id, username, password) values (231, 'slambdean6e', 'iM8odnxp81y');
insert into customer (id, username, password) values (232, 'mdachey6f', 'uTp5eMPK9w4j');
insert into customer (id, username, password) values (233, 'vchapling6g', 'M3VCs1nFpaWx');
insert into customer (id, username, password) values (234, 'gdelgaty6h', 'RWxZLckz');
insert into customer (id, username, password) values (235, 'bcroad6i', '3OaHltG2');
insert into customer (id, username, password) values (236, 'atipple6j', 'CddeH1sVY');
insert into customer (id, username, password) values (237, 'rdorkin6k', 'AUi0LslZ');
insert into customer (id, username, password) values (238, 'cbullivant6l', 'r5GAid');
insert into customer (id, username, password) values (239, 'aodennehy6m', 'cILWrKka2');
insert into customer (id, username, password) values (240, 'nleuren6n', 'XfxvFSb');
insert into customer (id, username, password) values (241, 'bmillis6o', '38IcNVFxm69S');