package someKindOfShop.DAO;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;

import someKindOfShop.shoppingList.Items;
import someKindOfShop.shoppingList.Offers;
import someKindOfShop.user.Customer;
import someKindOfShop.util.ConnectionUtil;

public class OfferPostgres implements OfferDAO {

	@Override
	public Offers addOffer(Offers f) {
		String sql = "insert into offer (c_id, i_id ,amount) values (?,?,?) returning id;";
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setInt(1, f.getCustomerId());
			ps.setInt(2, f.getItemId());
			ps.setInt(3, f.getAmount());
			
			ResultSet rs = ps.executeQuery(); // return the id generated by the database
			if(rs.next()){
				f.setCustomerId(rs.getInt("id"));
			}
			
		} catch (SQLException ex) {
			// TODO Auto-generated catch block
			ex.printStackTrace();
		}
		
		return f;
	}

	@Override
	public List<Offers> retrieveOffers() {
		String sql = "select * from offer;";
		List<Offers> items = new ArrayList<>();
		
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			// no user input taken, no need for prepared statement
			Statement s = c.createStatement();
			ResultSet rs = s.executeQuery(sql);
			
			while(rs.next()) {
				// extract each field from rs for each record, map them to a User object and add them to the users arrayliost
				Offers u = new Offers();
				u.setId(rs.getInt("id"));
				u.setCustomerId(rs.getInt("c_id"));
				u.setItemId(rs.getInt("i_id"));
				u.setAmount(rs.getInt("amount"));
				u.setAccepted(rs.getBoolean("accepted"));
				
				items.add(u);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return items;
	}
	@Override
	public List<Offers> retrieveAcceptedOffers() {
		String sql = "select * from offer where accepted = true;";
		List<Offers> items = new ArrayList<>();
		
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			// no user input taken, no need for prepared statement
			Statement s = c.createStatement();
			ResultSet rs = s.executeQuery(sql);
			
			while(rs.next()) {
				// extract each field from rs for each record, map them to a User object and add them to the users arrayliost
				Offers u = new Offers();
				u.setId(rs.getInt("id"));
				u.setCustomerId(rs.getInt("c_id"));
				u.setItemId(rs.getInt("i_id"));
				u.setAmount(rs.getInt("amount"));
				u.setAccepted(rs.getBoolean("accepted"));
		
				items.add(u);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return items;
	}
	public List<Integer> retrieveWeeklyPay(Date sd,Date ed){
		
		String sql="select amount from offer where offer_date >= ? and offer_date <= ?;";
         List<Integer> payments = new ArrayList<>();
		
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			
			ps.setDate(1, sd); // this refers to the 1st ? in the sql String
			ps.setDate(2, ed);
			ResultSet rs = ps.executeQuery();
			
			while(rs.next()) {
				Offers offer = new Offers();
				offer.setAmount(rs.getInt("amount"));
				payments.add(offer.getAmount());
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return payments;
		
	}
	@Override
	public int sumOfPayments() {
		String sql = "select sum(amount) as total from offer where accepted = true;";
		int total = 0;
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);		
			ResultSet rs = ps.executeQuery();
			
			if(rs.next()) {
				
				total = rs.getInt("total");
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return total;
	}
	@Override
	public boolean setAcceptedDate(int cId,int iId,Date d) {
		
		String sql = "update offer set offer_date = ? where accepted=true and c_id = ? and i_id=?;";
		int rowsChanged = -1;
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setDate(1,d);
			ps.setInt(2,cId);
			ps.setInt(3,iId);
			
		
			
			rowsChanged = ps.executeUpdate();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		if(rowsChanged < 1) {
			return false;
		}
		return true;
		
	}

	@Override
	public Offers retrieveOfferById(int id) {
		String sql = "select * from offer where id = ?;";
		Offers offer = null;
		
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			
			ps.setInt(1, id); // this refers to the 1st ? in the sql String
			
			ResultSet rs = ps.executeQuery();
			
			if(rs.next()) {
				offer = new Offers();
				offer.setItemId(rs.getInt("i_id"));
				offer.setCustomerId(rs.getInt("c_id"));
				offer.setAmount(rs.getInt("amount"));
				offer.setAccepted(rs.getBoolean("accepted"));
				offer.setId(rs.getInt("id"));
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return offer;
	}

	@Override
	public List<Offers> retrieveOfferByUserId(int id) {
		String sql = "select t.id, t.i_name, t.owned_state, t.customer_id,t.accepted , c.username from items t join customer c on t.customer_id = c.id where c.id = ?;";
		List<Offers> items = new ArrayList<>();
		
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setInt(1, id);
			
			ResultSet rs = ps.executeQuery();
			
			while(rs.next()) {
				Offers t = new Offers();
				t.setId(rs.getInt("id"));
				t.setCustomerId(rs.getInt("customer_id"));
				//t.setDueDate(rs.getDate("due_date").toLocalDate()); // rs.getDate returns a date that we have to convert to a local date
				t.setItemId(rs.getInt("item_id"));
				t.setAccepted(rs.getBoolean("accepted"));
				
				Customer u = new Customer();
				u.setId(rs.getInt("customer_id"));
				u.setUname(rs.getString("username"));
				
				//t.setUserAssigned(u);
				
				items.add(t);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return items;
	}

	

	@Override
	public boolean deleteOffer(int id) {
		String sql = "delete from offer where id = ?;";
		int rowsChanged = -1;
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			
			ps.setInt(1, id);
			
			rowsChanged = ps.executeUpdate();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		if(rowsChanged < 1) {
			return false;
		}
		return true;
	}
	@Override
	public boolean updateAcceptedState(int cId, int iId,boolean acc) {
		String sql = "update offer set accepted = ? where c_id = ? and i_id=?;";
		int rowsChanged = -1;
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setBoolean(1, acc);
			ps.setInt(2, cId);
			ps.setInt(3, iId);
			
			rowsChanged = ps.executeUpdate();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		if(rowsChanged < 1) {
			return false;
		}
		return true;
	}
	@Override
	public boolean rejectAllOffersByItemId(int iId) {
		String sql = "delete from offer where i_id=? and (accepted = false or accepted is null) ;";
		int rowsChanged = -1;
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setInt(1, iId);
			
			
			rowsChanged = ps.executeUpdate();
			
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		if(rowsChanged < 1) {
			return false;
		}
		return true;
	}
	@Override
	public int getAmount(int cId,int iId) {
		int amnt=0;
		String sql = "select amount from offer where c_id=? and i_id = ? ;";
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setInt(1, cId);
			ps.setInt(2, iId);
			ResultSet rs = ps.executeQuery();
			while(rs.next()) {
			
			Offers o=new Offers();
			o.setAmount(rs.getInt("amount"));
			amnt= o.getAmount();
			}
		}catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		
		return amnt;
		
	}

	@Override
	public List<Items> retrieveItemByUserId(int userId) {
		String sql = "select t.i_id, c.i_name, c.owned_state from offer t join items c on t.i_id = c.id where t.c_id = ?;";
		List<Items> items = new ArrayList<>();
		
		try(Connection c = ConnectionUtil.getConnectionFromEnv()){
			PreparedStatement ps = c.prepareStatement(sql);
			ps.setInt(1, userId);
			
			ResultSet rs = ps.executeQuery();
			
			while(rs.next()) {
				Items t = new Items();
				t.setId(rs.getInt("i_id"));
				t.setName(rs.getString("i_name"));
				//t.setDueDate(rs.getDate("due_date").toLocalDate()); // rs.getDate returns a date that we have to convert to a local date
				t.setOwenedStatus(rs.getString("owned_state"));
			
				
				items.add(t);
			}
		} catch (SQLException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return items;
	}
 

}
